/*
RowBuffer * 	 LCD5x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Mirosław Kardaś
 */
//#include <avr/io.h>
//#include <avr/pgmspace.h>
#include "../../../libs/SW_GRAPHICS/fonts_common.h"

//  Font data for LCD5x8


// Character bitmaps for LCD5x8

const uint8_t MagicMatrix_3x5_Bitmaps[]  = {
	0x40,0xA0,0xA0,0xA0,0x40,                     // char 0  (48)
	0x40,0xC0,0x40,0x40,0xE0,                     // char 1  (49)
	0xE0,0x20,0xE0,0x80,0xE0,                     // char 2  (50)
	0xE0,0x20,0xE0,0x20,0xE0,                     // char 3  (51)
	0x20,0x60,0xA0,0xE0,0x20,                     // char 4  (52)
	0xE0,0x80,0xE0,0x20,0xE0,                     // char 5  (53)
	0xE0,0x80,0xE0,0xA0,0xE0,                     // char 6  (54)
	0xE0,0x20,0x20,0x40,0x40,                     // char 7  (55)
	0xE0,0xA0,0xE0,0xA0,0xE0,                     // char 8  (56)
	0xE0,0xA0,0xE0,0x20,0xE0,                     // char 9  (57)
	0x00,0x40,0x00,0x40,0x00,                     // char :  (58)
};

// descriptors
const FONT_CHAR_INFO MagicMatrix_3x5_Descriptors[]  = {
	{ 3,0 },	// 0  (48)
	{ 3,5 },	// 1  (49)
	{ 3,10 },	// 2  (50)
	{ 3,15 },	// 3  (51)
	{ 3,20 },	// 4  (52)
	{ 3,25 },	// 5  (53)
	{ 3,30 },	// 6  (54)
	{ 3,35 },	// 7  (55)
	{ 3,40 },	// 8  (56)
	{ 3,45 },	// 9  (57)
	{ 3,50 },	// :  (58)
};

// Font information
const FONT_INFO MagicMatrix_3x5_FontInfo  = {
	5,								// Character height
	'0',							// Start character
	1,								// number of pixels of interspace between characters
	1,								// number of pixels of space character
	MagicMatrix_3x5_Descriptors,	//
	MagicMatrix_3x5_Bitmaps,		// number of pixels of space character
//	0,								// (Pointer) Font filename saved on SD card or 0 (null) otherwise  )
	sizeof(MagicMatrix_3x5_Descriptors) / sizeof(MagicMatrix_3x5_Descriptors[0]),
};
