/*
RowBuffer * 	 LCD5x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Mirosław Kardaś
 */
//#include <avr/io.h>
//#include <avr/pgmspace.h>
#include "../../../libs/SW_GRAPHICS/fonts_common.h"

//  Font data for LCD5x8


// Character bitmaps for LCD5x8

const uint8_t MagicMatrix_3x7_Bitmaps[]  = {
	0x40,0xA0,0xA0,0xA0,0xA0,0xA0,0x40,           // char 0  (48)
	0x20,0x60,0xA0,0x20,0x20,0x20,0x20,           // char 1  (49)
	0x40,0xA0,0x20,0x40,0x80,0x80,0xE0,           // char 2  (50)
	0x40,0xA0,0x20,0x40,0x20,0xA0,0x40,           // char 3  (51)
	0x20,0x40,0x80,0xE0,0x20,0x20,0x20,           // char 4  (52)
	0xE0,0x80,0x80,0x40,0x20,0xA0,0x40,           // char 5  (53)
	0x40,0xA0,0x80,0xC0,0xA0,0xA0,0x40,           // char 6  (54)
	0xE0,0x20,0x20,0x40,0x40,0x80,0x80,           // char 7  (55)
	0x40,0xA0,0xA0,0x40,0xA0,0xA0,0x40,           // char 8  (56)
	0x40,0xA0,0xA0,0x60,0x20,0xA0,0x40,           // char 9  (57)
	0x00,0x00,0x40,0x00,0x40,0x00,0x00,           // char :  (58)
};

// descriptors
const FONT_CHAR_INFO MagicMatrix_3x7_Descriptors[]  = {
	{ 3,0 },	// 0  (48)
	{ 3,7 },	// 1  (49)
	{ 3,14 },	// 2  (50)
	{ 3,21 },	// 3  (51)
	{ 3,28 },	// 4  (52)
	{ 3,35 },	// 5  (53)
	{ 3,42 },	// 6  (54)
	{ 3,49 },	// 7  (55)
	{ 3,56 },	// 8  (56)
	{ 3,63 },	// 9  (57)
	{ 3,70 },	// :  (58)
};

// Font information
const FONT_INFO MagicMatrix_3x7_FontInfo  = {
	7,								// Character height
	'0',							// Start character
	1,								// number of pixels of interspace between characters
	1,								// number of pixels of space character
	MagicMatrix_3x7_Descriptors,	//
	MagicMatrix_3x7_Bitmaps,		// number of pixels of space character
//	0,								// (Pointer) Font filename saved on SD card or 0 (null) otherwise  )
	sizeof(MagicMatrix_3x7_Descriptors) / sizeof(MagicMatrix_3x7_Descriptors[0]),
};
