/*
 * 	 DefaultFont5x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Miros�aw Karda�
 */
#ifdef __AVR__
#include <avr/io.h>
#include <avr/pgmspace.h>
#elif defined STM32F3 || defined STM32L4
#include "sw_mcu_conf.h"
#include "../../SW_BOARD/sw_gpio.h"
#include "../../SW_TIMERS/sw_soft_timers.h"
#define PROGMEM
#define pgm_read_byte	*
#define _delay_ms		delay_ms
#endif

#include "mk_fonts.h"


//  Font data for DefaultFont5x8


// Character bitmaps for DefaultFont5x8
const uint8_t DefaultFont5x8Bitmaps[] PROGMEM = {
	0x5F,                                          // char !  (33)
	0x03, 0x00, 0x03,                                // char "  (34)
	0x14, 0x7F, 0x14, 0x7F, 0x14,                      // char #  (35)
	0x24, 0x4A, 0xFF, 0x52, 0x24,                      // char $  (36)
	0x23, 0x13, 0x08, 0x64, 0x62,                      // char %  (37)
	0x36, 0x49, 0x55, 0x22, 0x50,                      // char &  (38)
	0x03,                                          // char '  (39)
	0x1C, 0x22, 0x41,                                // char (  (40)
	0x41, 0x22, 0x1C,                                // char )  (41)
	0x14, 0x08, 0x3E, 0x08, 0x14,                      // char *  (42)
	0x08, 0x08, 0x3E, 0x08, 0x08,                      // char +  (43)
	0x80, 0x60,                                     // char ,  (44)
	0x08, 0x08, 0x08, 0x08, 0x08,                      // char -  (45)
	0x40,                                          // char .  (46)
	0x20, 0x10, 0x08, 0x04, 0x02,                      // char /  (47)
	0x3E, 0x51, 0x49, 0x45, 0x3E,                      // char 0  (48)
	0x00, 0x42, 0x7F, 0x40, 0x00,                      // char 1  (49)
	0x72, 0x49, 0x49, 0x49, 0x46,                      // char 2  (50)
	0x22, 0x41, 0x49, 0x49, 0x36,                      // char 3  (51)
	0x18, 0x14, 0x12, 0x11, 0x7F,                      // char 4  (52)
	0x27, 0x45, 0x45, 0x45, 0x39,                      // char 5  (53)
	0x3E, 0x49, 0x49, 0x49, 0x32,                      // char 6  (54)
	0x03, 0x01, 0x71, 0x0D, 0x03,                      // char 7  (55)
	0x36, 0x49, 0x49, 0x49, 0x36,                      // char 8  (56)
	0x26, 0x49, 0x49, 0x49, 0x3E,                      // char 9  (57)
	0x00, 0x00, 0x24, 0x00, 0x00,                      // char :  (58)
	0x00, 0x80, 0x64, 0x00, 0x00,                      // char ;  (59)
	0x08, 0x14, 0x22, 0x41,                           // char <  (60)
	0x14, 0x14, 0x14, 0x14,                           // char =  (61)
	0x41, 0x22, 0x14, 0x08,                           // char >  (62)
	0x02, 0x01, 0x51, 0x09, 0x06,                      // char ?  (63)
	0x3E, 0x41, 0x5D, 0x51, 0x5E,                      // char @  (64)
	0x7C, 0x12, 0x11, 0x12, 0x7C,                      // char A  (65)
	0x7F, 0x49, 0x49, 0x49, 0x36,                      // char B  (66)
	0x3E, 0x41, 0x41, 0x41, 0x22,                      // char C  (67)
	0x7F, 0x41, 0x41, 0x41, 0x3E,                      // char D  (68)
	0x7F, 0x49, 0x49, 0x49, 0x41,                      // char E  (69)
	0x7F, 0x09, 0x09, 0x09, 0x01,                      // char F  (70)
	0x3E, 0x41, 0x41, 0x51, 0x32,                      // char G  (71)
	0x7F, 0x08, 0x08, 0x08, 0x7F,                      // char H  (72)
	0x41, 0x7F, 0x41,                                // char I  (73)
	0x20, 0x41, 0x41, 0x3F,                           // char J  (74)
	0x7F, 0x08, 0x14, 0x22, 0x41,                      // char K  (75)
	0x7F, 0x40, 0x40, 0x40,                           // char L  (76)
	0x7F, 0x02, 0x0C, 0x02, 0x7F,                      // char M  (77)
	0x7F, 0x06, 0x08, 0x30, 0x7F,                      // char N  (78)
	0x3E, 0x41, 0x41, 0x41, 0x3E,                      // char O  (79)
	0x7F, 0x11, 0x11, 0x11, 0x0E,                      // char P  (80)
	0x3E, 0x41, 0x61, 0x41, 0xBE,                      // char Q  (81)
	0x7F, 0x11, 0x11, 0x31, 0x4E,                      // char R  (82)
	0x26, 0x49, 0x49, 0x49, 0x32,                      // char S  (83)
	0x01, 0x01, 0x7F, 0x01, 0x01,                      // char T  (84)
	0x3F, 0x40, 0x40, 0x40, 0x3F,                      // char U  (85)
	0x1F, 0x20, 0x40, 0x20, 0x1F,                      // char V  (86)
	0x7F, 0x20, 0x18, 0x20, 0x7F,                      // char W  (87)
	0x63, 0x14, 0x08, 0x14, 0x63,                      // char X  (88)
	0x07, 0x08, 0x70, 0x08, 0x07,                      // char Y  (89)
	0x61, 0x51, 0x49, 0x45, 0x43,                      // char Z  (90)
	0xFF, 0x81, 0x81,                                // char [  (91)
	0x02, 0x04, 0x08, 0x10, 0x20,                      // char \  (92)
	0x81, 0x81, 0xFF,                                // char ]  (93)
	0x02, 0x01, 0x02,                                // char ^  (94)
	0x80, 0x80, 0x80, 0x80, 0x80,                      // char _  (95)
	0x01, 0x02,                                     // char `  (96)
	0x20, 0x54, 0x54, 0x78,                           // char a  (97)
	0x7F, 0x44, 0x44, 0x38,                           // char b  (98)
	0x38, 0x44, 0x44, 0x28,                           // char c  (99)
	0x38, 0x44, 0x44, 0x7F,                           // char d  (100)
	0x38, 0x54, 0x54, 0x58,                           // char e  (101)
	0x08, 0x7E, 0x09, 0x09,                           // char f  (102)
	0x18, 0xA4, 0xA4, 0x7C,                           // char g  (103)
	0x7F, 0x04, 0x04, 0x78,                           // char h  (104)
	0x44, 0x7D, 0x40,                                // char i  (105)
	0x80, 0x84, 0x7D,                                // char j  (106)
	0x7F, 0x10, 0x28, 0x44,                           // char k  (107)
	0x41, 0x7F, 0x40,                                // char l  (108)
	0x7C, 0x04, 0x7C, 0x04, 0x78,                      // char m  (109)
	0x7C, 0x04, 0x04, 0x78,                           // char n  (110)
	0x38, 0x44, 0x44, 0x38,                           // char o  (111)
	0xFC, 0x44, 0x44, 0x38,                           // char p  (112)
	0x38, 0x44, 0x44, 0xFC,                           // char q  (113)
	0x04, 0x78, 0x04, 0x04,                           // char r  (114)
	0x08, 0x54, 0x54, 0x20,                           // char s  (115)
	0x04, 0x3E, 0x44, 0x44,                           // char t  (116)
	0x3C, 0x40, 0x40, 0x7C,                           // char u  (117)
	0x1C, 0x20, 0x40, 0x20, 0x1C,                      // char v  (118)
	0x3C, 0x40, 0x30, 0x40, 0x3C,                      // char w  (119)
	0x44, 0x28, 0x10, 0x28, 0x44,                      // char x  (120)
	0x1C, 0xA0, 0xA0, 0x7C,                           // char y  (121)
	0x44, 0x64, 0x54, 0x4C,                           // char z  (122)
	0x08, 0x36, 0x41,                                // char {  (123)
	0xFF,                                          // char |  (124)
	0x41, 0x36, 0x08,                                // char }  (125)
	0x04, 0x02, 0x04, 0x02,                           // char    (126)
	0x80, 0x60,                                     // char    (130)
	0x24, 0x4A, 0x4B, 0x4A, 0x30,                      // char �  (140)
	0x42, 0x66, 0x53, 0x4A, 0x46,                      // char �  (143)
	0x02, 0x07, 0x02,                                // char    (149)
	0x22, 0x14, 0x08,                                // char    (155)
	0x48, 0x54, 0x56, 0x25,                           // char �  (156)
	0x44, 0x64, 0x56, 0x4D,                           // char �  (159)
	0x7F, 0x50, 0x48, 0x44,                           // char    (163)
	0x7C, 0x12, 0x11, 0x92, 0x7C,                      // char �  (165)
	0x3C, 0x42, 0x99, 0xA5, 0xA5, 0x81, 0x42, 0x3C,       // char    (169)
	0x08, 0x14, 0x00, 0x08, 0x14,                      // char    (171)
	0x69, 0x59, 0x49, 0x4D, 0x4B,                      // char �  (175)
	0x06, 0x09, 0x09, 0x06,                           // char    (176)
	0x24, 0x2E, 0x24,                                // char    (177)
	0x49, 0x7F, 0x44,                                // char    (179)
	0xFC, 0x20, 0x40, 0x3C,                           // char    (181)
	0x20, 0x54, 0xD4, 0x78,                           // char �  (185)
	0x14, 0x08, 0x00, 0x14, 0x08,                      // char    (187)
	0x44, 0x64, 0x55, 0x4C,                           // char �  (191)
	0x7F, 0x49, 0x49, 0xC9, 0x61,                      // char �  (202)
	0x3C, 0x42, 0x47, 0x42, 0x3C,                      // char �  (211)
	0x38, 0x44, 0x46, 0x29,                           // char �  (230)
	0x38, 0x54, 0x54, 0xD8,                           // char �  (234)
	0x7C, 0x06, 0x05, 0x78,                           // char �  (241)
	0x38, 0x44, 0x46, 0x39,                           // char �  (243)
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF,                      // char    (255)
};

// descriptors
const FONT_CHAR_INFO DefaultFont5x8Descriptors[] PROGMEM = {
	{ 1,0 },	// char !  (33)
	{ 3,1 },	// char "  (34)
	{ 5,4 },	// char #  (35)
	{ 5,9 },	// char $  (36)
	{ 5,14 },	// char %  (37)
	{ 5,19 },	// char &  (38)
	{ 1,24 },	// char '  (39)
	{ 3,25 },	// char (  (40)
	{ 3,28 },	// char )  (41)
	{ 5,31 },	// char *  (42)
	{ 5,36 },	// char +  (43)
	{ 2,41 },	// char ,  (44)
	{ 5,43 },	// char -  (45)
	{ 1,48 },	// char .  (46)
	{ 5,49 },	// char /  (47)
	{ 5,54 },	// char 0  (48)
	{ 5,59 },	// char 1  (49)
	{ 5,64 },	// char 2  (50)
	{ 5,69 },	// char 3  (51)
	{ 5,74 },	// char 4  (52)
	{ 5,79 },	// char 5  (53)
	{ 5,84 },	// char 6  (54)
	{ 5,89 },	// char 7  (55)
	{ 5,94 },	// char 8  (56)
	{ 5,99 },	// char 9  (57)
	{ 5,104 },	// char :  (58)
	{ 5,109 },	// char ;  (59)
	{ 4,114 },	// char <  (60)
	{ 4,118 },	// char =  (61)
	{ 4,122 },	// char >  (62)
	{ 5,126 },	// char ?  (63)
	{ 5,131 },	// char @  (64)
	{ 5,136 },	// char A  (65)
	{ 5,141 },	// char B  (66)
	{ 5,146 },	// char C  (67)
	{ 5,151 },	// char D  (68)
	{ 5,156 },	// char E  (69)
	{ 5,161 },	// char F  (70)
	{ 5,166 },	// char G  (71)
	{ 5,171 },	// char H  (72)
	{ 3,176 },	// char I  (73)
	{ 4,179 },	// char J  (74)
	{ 5,183 },	// char K  (75)
	{ 4,188 },	// char L  (76)
	{ 5,192 },	// char M  (77)
	{ 5,197 },	// char N  (78)
	{ 5,202 },	// char O  (79)
	{ 5,207 },	// char P  (80)
	{ 5,212 },	// char Q  (81)
	{ 5,217 },	// char R  (82)
	{ 5,222 },	// char S  (83)
	{ 5,227 },	// char T  (84)
	{ 5,232 },	// char U  (85)
	{ 5,237 },	// char V  (86)
	{ 5,242 },	// char W  (87)
	{ 5,247 },	// char X  (88)
	{ 5,252 },	// char Y  (89)
	{ 5,257 },	// char Z  (90)
	{ 3,262 },	// char [  (91)
	{ 5,265 },	// char \  (92)
	{ 3,270 },	// char ]  (93)
	{ 3,273 },	// char ^  (94)
	{ 5,276 },	// char _  (95)
	{ 2,281 },	// char `  (96)
	{ 4,283 },	// char a  (97)
	{ 4,287 },	// char b  (98)
	{ 4,291 },	// char c  (99)
	{ 4,295 },	// char d  (100)
	{ 4,299 },	// char e  (101)
	{ 4,303 },	// char f  (102)
	{ 4,307 },	// char g  (103)
	{ 4,311 },	// char h  (104)
	{ 3,315 },	// char i  (105)
	{ 3,318 },	// char j  (106)
	{ 4,321 },	// char k  (107)
	{ 3,325 },	// char l  (108)
	{ 5,328 },	// char m  (109)
	{ 4,333 },	// char n  (110)
	{ 4,337 },	// char o  (111)
	{ 4,341 },	// char p  (112)
	{ 4,345 },	// char q  (113)
	{ 4,349 },	// char r  (114)
	{ 4,353 },	// char s  (115)
	{ 4,357 },	// char t  (116)
	{ 4,361 },	// char u  (117)
	{ 5,365 },	// char v  (118)
	{ 5,370 },	// char w  (119)
	{ 5,375 },	// char x  (120)
	{ 4,380 },	// char y  (121)
	{ 4,384 },	// char z  (122)
	{ 3,388 },	// char {  (123)
	{ 1,391 },	// char |  (124)
	{ 3,392 },	// char }  (125)
	{ 4,395 },	// char    (126)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 2,399 },	// char    (130)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 5,401 },	// char �  (140)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 5,406 },	// char �  (143)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 3,411 },	// char    (149)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 3,414 },	// char    (155)
	{ 4,417 },	// char �  (156)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,421 },	// char �  (159)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,425 },	// char    (163)
	{ 0,0 },	//
	{ 5,429 },	// char �  (165)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 8,434 },	// char    (169)
	{ 0,0 },	//
	{ 5,442 },	// char    (171)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 5,447 },	// char �  (175)
	{ 4,452 },	// char    (176)
	{ 3,456 },	// char    (177)
	{ 0,0 },	//
	{ 3,459 },	// char    (179)
	{ 0,0 },	//
	{ 4,462 },	// char    (181)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,466 },	// char �  (185)
	{ 0,0 },	//
	{ 5,470 },	// char    (187)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,475 },	// char �  (191)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 5,479 },	// char �  (202)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 5,484 },	// char �  (211)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,489 },	// char �  (230)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,493 },	// char �  (234)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 4,497 },	// char �  (241)
	{ 0,0 },	//
	{ 4,501 },	// char �  (243)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 0,0 },	//
	{ 5,505 },	// char    (255)
};

// Font information
const FONT_INFO DefaultFont5x8 PROGMEM = {
	0,	// Down Space in pixels
	8,	// Caracter height
	'!',	// Start character
	2,	// number of pixels of interspace between characters
	2,	// number of pixels of space character
	DefaultFont5x8Descriptors,	// number of pixels of space character
	DefaultFont5x8Bitmaps,	// number of pixels of space character
	0,	// (Pointer) Font filename saved on SD card or 0 (null) otherwise  )
	0,	// bits and byte orientation 0-T2B, 1-L2R
};
