/*
 * 	 MkMINI3x6.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Miros�aw Karda�
 */
#ifdef __AVR__
#include <avr/io.h>
#include <avr/pgmspace.h>
#elif defined STM32F3 || defined STM32L4
#include "sw_mcu_conf.h"
#include "../../SW_BOARD/sw_gpio.h"
#include "../../SW_TIMERS/sw_soft_timers.h"
#define PROGMEM
#define pgm_read_byte	*
#define _delay_ms		delay_ms
#endif

#include "mk_fonts.h"


//  Font data for MkMINI3x6


// Character bitmaps for MkMINI3x6
const uint8_t MkMINI3x6Bitmaps[] PROGMEM = {
	0x00,0x17,0x00,                               // char !  (33)
	0x03,0x00,0x03,                               // char "  (34)
	0x19,0x04,0x13,                               // char %  (37)
	0x00,0x03,0x00,                               // char '  (39)
	0x0C,0x12,0x21,                               // char (  (40)
	0x21,0x12,0x0C,                               // char )  (41)
	0x0A,0x04,0x0A,                               // char *  (42)
	0x04,0x0E,0x04,                               // char +  (43)
	0x20,0x10,0x00,                               // char ,  (44)
	0x04,0x04,0x04,                               // char -  (45)
	0x00,0x10,0x00,                               // char .  (46)
	0x30,0x0C,0x03,                               // char /  (47)
	0x1F,0x11,0x1F,                               // char 0  (48)
	0x12,0x1F,0x10,                               // char 1  (49)
	0x1D,0x15,0x17,                               // char 2  (50)
	0x15,0x15,0x1F,                               // char 3  (51)
	0x07,0x04,0x1F,                               // char 4  (52)
	0x17,0x15,0x1D,                               // char 5  (53)
	0x1F,0x15,0x1D,                               // char 6  (54)
	0x03,0x19,0x07,                               // char 7  (55)
	0x1F,0x15,0x1F,                               // char 8  (56)
	0x17,0x15,0x1F,                               // char 9  (57)
	0x00,0x0A,0x00,                               // char :  (58)
	0x20,0x14,0x00,                               // char ;  (59)
	0x04,0x0A,0x11,                               // char <  (60)
	0x0A,0x0A,0x0A,                               // char =  (61)
	0x11,0x0A,0x04,                               // char >  (62)
	0x02,0x29,0x06,                               // char ?  (63)
	0x1E,0x09,0x1E,                               // char A  (65)
	0x1F,0x15,0x0A,                               // char B  (66)
	0x0E,0x11,0x0A,                               // char C  (67)
	0x1F,0x11,0x0E,                               // char D  (68)
	0x1F,0x15,0x11,                               // char E  (69)
	0x1F,0x05,0x01,                               // char F  (70)
	0x0E,0x15,0x0C,                               // char G  (71)
	0x1F,0x04,0x1F,                               // char H  (72)
	0x11,0x1F,0x11,                               // char I  (73)
	0x21,0x21,0x1F,                               // char J  (74)
	0x1F,0x04,0x1B,                               // char K  (75)
	0x1F,0x10,0x10,                               // char L  (76)
	0x1F,0x02,0x1F,                               // char M  (77)
	0x1F,0x06,0x1F,                               // char N  (78)
	0x0E,0x11,0x0E,                               // char O  (79)
	0x1F,0x09,0x06,                               // char P  (80)
	0x0E,0x11,0x2E,                               // char Q  (81)
	0x1F,0x09,0x16,                               // char R  (82)
	0x12,0x15,0x09,                               // char S  (83)
	0x01,0x1F,0x01,                               // char T  (84)
	0x1F,0x10,0x1F,                               // char U  (85)
	0x0F,0x18,0x0F,                               // char V  (86)
	0x1F,0x08,0x1F,                               // char W  (87)
	0x1B,0x04,0x1B,                               // char X  (88)
	0x03,0x1C,0x03,                               // char Y  (89)
	0x19,0x15,0x13,                               // char Z  (90)
	0x3F,0x21,0x21,                               // char [  (91)
	0x03,0x0C,0x30,                               // char \  (92)
	0x21,0x21,0x3F,                               // char ]  (93)
	0x02,0x05,0x02,                               // char ^  (94)
	0x20,0x20,0x20,                               // char _  (95)
	0x00,0x03,0x00,                               // char `  (96)
	0x09,0x15,0x1E,                               // char a  (97)
	0x1F,0x12,0x0C,                               // char b  (98)
	0x0C,0x12,0x12,                               // char c  (99)
	0x0C,0x12,0x1F,                               // char d  (100)
	0x0E,0x15,0x16,                               // char e  (101)
	0x04,0x1E,0x05,                               // char f  (102)
	0x24,0x2A,0x1E,                               // char g  (103)
	0x1F,0x02,0x1C,                               // char h  (104)
	0x00,0x1D,0x00,                               // char i  (105)
	0x20,0x1D,0x00,                               // char j  (106)
	0x1F,0x08,0x14,                               // char k  (107)
	0x11,0x1F,0x10,                               // char l  (108)
	0x1E,0x06,0x1E,                               // char m  (109)
	0x1E,0x02,0x1C,                               // char n  (110)
	0x0C,0x12,0x0C,                               // char o  (111)
	0x3E,0x12,0x0C,                               // char p  (112)
	0x04,0x0A,0x3E,                               // char q  (113)
	0x02,0x1C,0x02,                               // char r  (114)
	0x12,0x15,0x09,                               // char s  (115)
	0x02,0x0F,0x12,                               // char t  (116)
	0x0E,0x10,0x1E,                               // char u  (117)
	0x0E,0x10,0x0E,                               // char v  (118)
	0x1E,0x18,0x1E,                               // char w  (119)
	0x16,0x08,0x16,                               // char x  (120)
	0x26,0x28,0x1E,                               // char y  (121)
	0x19,0x15,0x13,                               // char z  (122)
	0x04,0x1B,0x11,                               // char {  (123)
	0x00,0x3F,0x00,                               // char |  (124)
	0x04,0x1B,0x11,                               // char }  (125)
	0x01,0x02,0x01,                               // char    (126)
};

// descriptors
const FONT_CHAR_INFO MkMINI3x6Descriptors[] PROGMEM = {
	{ 3,0 },	// char !  (33)
	{ 3,3 },	// char "  (34)
	{ 0,0 },	//
	{ 0,0 },	//
	{ 3,6 },	// char %  (37)
	{ 0,0 },	//
	{ 3,9 },	// char '  (39)
	{ 3,12 },	// char (  (40)
	{ 3,15 },	// char )  (41)
	{ 3,18 },	// char *  (42)
	{ 3,21 },	// char +  (43)
	{ 3,24 },	// char ,  (44)
	{ 3,27 },	// char -  (45)
	{ 3,30 },	// char .  (46)
	{ 3,33 },	// char /  (47)
	{ 3,36 },	// char 0  (48)
	{ 3,39 },	// char 1  (49)
	{ 3,42 },	// char 2  (50)
	{ 3,45 },	// char 3  (51)
	{ 3,48 },	// char 4  (52)
	{ 3,51 },	// char 5  (53)
	{ 3,54 },	// char 6  (54)
	{ 3,57 },	// char 7  (55)
	{ 3,60 },	// char 8  (56)
	{ 3,63 },	// char 9  (57)
	{ 3,66 },	// char :  (58)
	{ 3,69 },	// char ;  (59)
	{ 3,72 },	// char <  (60)
	{ 3,75 },	// char =  (61)
	{ 3,78 },	// char >  (62)
	{ 3,81 },	// char ?  (63)
	{ 0,0 },	//
	{ 3,84 },	// char A  (65)
	{ 3,87 },	// char B  (66)
	{ 3,90 },	// char C  (67)
	{ 3,93 },	// char D  (68)
	{ 3,96 },	// char E  (69)
	{ 3,99 },	// char F  (70)
	{ 3,102 },	// char G  (71)
	{ 3,105 },	// char H  (72)
	{ 3,108 },	// char I  (73)
	{ 3,111 },	// char J  (74)
	{ 3,114 },	// char K  (75)
	{ 3,117 },	// char L  (76)
	{ 3,120 },	// char M  (77)
	{ 3,123 },	// char N  (78)
	{ 3,126 },	// char O  (79)
	{ 3,129 },	// char P  (80)
	{ 3,132 },	// char Q  (81)
	{ 3,135 },	// char R  (82)
	{ 3,138 },	// char S  (83)
	{ 3,141 },	// char T  (84)
	{ 3,144 },	// char U  (85)
	{ 3,147 },	// char V  (86)
	{ 3,150 },	// char W  (87)
	{ 3,153 },	// char X  (88)
	{ 3,156 },	// char Y  (89)
	{ 3,159 },	// char Z  (90)
	{ 3,162 },	// char [  (91)
	{ 3,165 },	// char \  (92)
	{ 3,168 },	// char ]  (93)
	{ 3,171 },	// char ^  (94)
	{ 3,174 },	// char _  (95)
	{ 3,177 },	// char `  (96)
	{ 3,180 },	// char a  (97)
	{ 3,183 },	// char b  (98)
	{ 3,186 },	// char c  (99)
	{ 3,189 },	// char d  (100)
	{ 3,192 },	// char e  (101)
	{ 3,195 },	// char f  (102)
	{ 3,198 },	// char g  (103)
	{ 3,201 },	// char h  (104)
	{ 3,204 },	// char i  (105)
	{ 3,207 },	// char j  (106)
	{ 3,210 },	// char k  (107)
	{ 3,213 },	// char l  (108)
	{ 3,216 },	// char m  (109)
	{ 3,219 },	// char n  (110)
	{ 3,222 },	// char o  (111)
	{ 3,225 },	// char p  (112)
	{ 3,228 },	// char q  (113)
	{ 3,231 },	// char r  (114)
	{ 3,234 },	// char s  (115)
	{ 3,237 },	// char t  (116)
	{ 3,240 },	// char u  (117)
	{ 3,243 },	// char v  (118)
	{ 3,246 },	// char w  (119)
	{ 3,249 },	// char x  (120)
	{ 3,252 },	// char y  (121)
	{ 3,255 },	// char z  (122)
	{ 3,258 },	// char {  (123)
	{ 3,261 },	// char |  (124)
	{ 3,264 },	// char }  (125)
	{ 3,267 },	// char    (126)
	{ 0,0 },	//
	{ 0,0 },	//
};

// Font information
const FONT_INFO MkMINI3x6 PROGMEM = {
	1,	// Down Space in pixels
	6,	// Caracter height
	'!',	// Start character
	1,	// number of pixels of interspace between characters
	3,	// number of pixels of space character
	MkMINI3x6Descriptors,	// number of pixels of space character
	MkMINI3x6Bitmaps,	// number of pixels of space character
	0,	// (Pointer) Font filename saved on SD card or 0 (null) otherwise  )
	0,	// bits and byte orientation 0-T2B, 1-L2R
};
